### ISSUE TITLE
Add keepLast option

### ISSUE THREAD

**Issue by ai** [logux/logux-core#15]
We need shortcut for

```js
  store.dispatch.crossTab(
    { type: 'amplifr/sync', state },
    { reasons: ['amplifr/lastSync'] }
  ).then(meta => {
    store.log.removeReason('amplifr/lastSync', { maxAdded: meta.added - 1 })
  })
```

Something like:

```js
  store.dispatch.crossTab(
    { type: 'amplifr/sync', state },
    { keepLast: 'amplifr/lastSync' }
  )
```

**Comment by rodweb** [comment]
Should `keepLast` be able to take in array (`keepLast: ['a', 'b']`), so that all actions having either one or both reasons were deleted? It may be useful to keep only the last action with one of several reasons in the log, and it seems to be not too hard to implement.

**Comment by ai** [comment]
@rodweb I don’t see use cases for it right now
