### ISSUE TITLE
Suggestion - Implement mergeLast

### ISSUE THREAD

**Issue by nevf** [logux/logux-core#18]
@ai  In addition to ```keepLast``` ex. ````log.add(action, { keepLast: 'app/lastName' })```` I can see a ```mergeLast``` capability being very useful.

For example if you have an object: ```doc: { id, date, completed, details, image )``` and:
1) ```date``` is updated. Then later on
2) ```completed``` is updated. Then later on
3) ```details``` is updated.

In this example the client only needs to update a single property for each update. And to minimize data sent to/from the server, only that single property needs to be part of the log ```action```.

However if ```keepLast``` is used and this client is 'offline', then log entries 1 & 2 will be lost _(cleaned)_ and only ```details``` will be updated when the client comes back 'online'

To resolve this ```mergeLast``` would merge the properties from the last log item with the one being added. So in the above example would result in: 
1) as above.
2)  ```completed``` is updated and ```date``` merged with it.
3)  ```details``` is updated and ```completed``` and ```date``` are merged with it.

This may need a callback to the client code to perform the actual merge as Logux may not be able to do it.

I understand that instead of just adding the single updated property to ```log.add()``` calls we can pass in the entire object which will resolve this issue. 

However if some object properties are large _(images,20K of html etc)_ then sending the entire object for every update is a waste of bandwidth, data, time etc. especially on mobile devices.

What do you think?

**Comment by ai** [comment]
It can be in `add()` method. Since this merge-action must be new. You must create a new a object and take deal with a lot of trade-offs.

The example:

1. `Time 1`. Changing date to `A`.
2. `Time 3`. Changing image.

Then we merge this 2 action into one. What time new action will have?

If we set `time 3`, then we could have a `time 2` action with date `B`. How we can merge new action correctly according `last write wins` if `date = A` new has `time 3` (later than `date = B`). But in the reality `date = B` was later than `date = A`.

So there is no one simple way to merge actions. This is why it should on application level or database-library level.

**Comment by nevf** [comment]
My thinking here is that it would be similar to ```keepLast```.  ```log.add()``` would always create a new entry and non of it's properties would be changed. 

Any existing matching log item would be removed _(same as ```keepLast```)_, after its log ```action``` properties were merged with the new action.  

Maybe my view of the world is too simple!

**Comment by ai** [comment]
Yeap, I understood your idea. The problem is that with this merge we will remove time of previous actions, which will make “last write wins” conflict resolution wrong.

**Comment by nevf** [comment]
Ok, you are saying that each individual ```action.property``` update needs to be logged so that "last write wins" at the ```action.property``` level. Whereas I was thinking of only tracking changes for the ```action`` object as a whole, in which case my merge idea might work. 

In you process I would need to get ```keepLast``` to track both the object.id and the name of the property that changed. So something like = ```keepLast: doc.id + property.name``` Is that right?

Now I need to go and think about this some more. :-)

**Comment by ai** [comment]
> keepLast: doc.id + property.name

Yeap

**Comment by nevf** [comment]
Ok, using ```keepLast: doc.id + property.name``` works for the _update_ individual properties case. 

A side issue is a _remove/delete_ action to remove the whole document, won't clean these _updates_ as it only specifies ```keepLast: doc.id```. The updates will get cleaned when the client comes back _online_, but they will also get sent to the server and other clients which is a waste. 

Any suggestions I how I can clean these unwanted updates from the log when a _remove_ action is done or should I leave the log alone and let the normal flow occur?

**Comment by ai** [comment]
For remove, you can just call `allProperties.forEach(prop => { log.removeReason(doc.id + prop) })`

**Comment by ai** [comment]
`keepLast` is just a shortcut, it is old reasons behind it :)
